"""
PDF Report Generator for INDRA
Generates technical assessment PDFs using ReportLab.
"""
import os
from datetime import datetime

class PDFGenerator:
    def create_technical_report(self, content: str, output_path: str, title: str = "Technical Assessment") -> str:
        """Creates a formatted technical PDF report."""
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import cm
            from reportlab.lib import colors
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
            from reportlab.lib.enums import TA_CENTER, TA_LEFT

            os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)
            doc = SimpleDocTemplate(output_path, pagesize=A4,
                                    rightMargin=2*cm, leftMargin=2*cm,
                                    topMargin=2*cm, bottomMargin=2*cm)

            styles = getSampleStyleSheet()
            title_style = ParagraphStyle("title", parent=styles["Title"],
                                         textColor=colors.HexColor("#1F3864"), fontSize=18, spaceAfter=12)
            heading_style = ParagraphStyle("heading", parent=styles["Heading2"],
                                           textColor=colors.HexColor("#2E4057"), fontSize=12, spaceAfter=6)
            body_style = styles["BodyText"]

            story = []
            story.append(Paragraph("INDRA SOVEREIGN ENGINEERING WORKBENCH", title_style))
            story.append(Paragraph(title, heading_style))
            story.append(Paragraph(f"Generated: {datetime.now().strftime('%d %B %Y %H:%M')}", body_style))
            story.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
            story.append(Spacer(1, 0.4*cm))

            for para in content.split("\n\n"):
                if para.strip():
                    story.append(Paragraph(para.strip().replace("\n", "<br/>"), body_style))
                    story.append(Spacer(1, 0.3*cm))

            story.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
            story.append(Spacer(1, 0.3*cm))
            story.append(Paragraph("⚠ This report is AI-generated and requires human review.", body_style))
            story.append(Paragraph("Generated by: INDRA Sovereign AI Workbench | 100% On-Premise", body_style))

            doc.build(story)
            return output_path
        except ImportError:
            return f"Error: reportlab not installed. Run: pip install reportlab"
        except Exception as e:
            return f"Error generating PDF: {str(e)}"

pdf_generator = PDFGenerator()
