"""
Word Document Generator for INDRA
Generates professional industrial engineering approval notes using python-docx.
"""
import os
from datetime import datetime

class WordGenerator:
    def create_approval_note(self, content: dict, output_path: str) -> str:
        """
        Creates a professional engineering approval note as a .docx file.
        content keys: title, equipment_tag, findings, calculations, recommendation,
                      evidence_sources, confidence, engineer_name
        """
        from docx import Document
        from docx.shared import Pt, RGBColor, Inches
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        doc = Document()

        # Header
        header = doc.add_heading("INDRA SOVEREIGN ENGINEERING WORKBENCH", level=1)
        header.alignment = WD_ALIGN_PARAGRAPH.CENTER

        subtitle = doc.add_paragraph("INDRA | Equipment Inspection Approval Note")
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

        doc.add_paragraph(f"Date: {datetime.now().strftime('%d %b %Y')}")
        doc.add_paragraph(f"Equipment Tag: {content.get('equipment_tag', 'N/A')}")
        doc.add_paragraph(f"Document Reference: {content.get('title', 'Approval Note')}")
        doc.add_paragraph("─" * 60)

        # Section 1: Findings
        doc.add_heading("1. Inspection Findings", level=2)
        findings = content.get("findings", [])
        if isinstance(findings, list):
            for f in findings:
                doc.add_paragraph(f"• {f}", style="List Bullet")
        else:
            doc.add_paragraph(str(findings))

        # Section 2: Calculations
        doc.add_heading("2. Engineering Calculations", level=2)
        calcs = content.get("calculations", "No calculations performed.")
        doc.add_paragraph(str(calcs))

        # Section 3: Evidence Sources
        doc.add_heading("3. Evidence Sources", level=2)
        sources = content.get("evidence_sources", [])
        if isinstance(sources, list):
            for s in sources:
                doc.add_paragraph(f"• {s}", style="List Bullet")
        else:
            doc.add_paragraph(str(sources))

        # Section 4: Recommendation
        doc.add_heading("4. Recommendation", level=2)
        rec_para = doc.add_paragraph(content.get("recommendation", "Further inspection required."))
        rec_para.runs[0].bold = True

        # Footer
        doc.add_paragraph("─" * 60)
        confidence = content.get("confidence", "N/A")
        doc.add_paragraph(f"AI Confidence Score: {confidence}")
        doc.add_paragraph(f"Generated by: INDRA Sovereign AI Workbench")
        doc.add_paragraph("⚠ This document requires human review and approval before any action.")

        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        doc.save(output_path)
        return output_path

    def create_simple_report(self, title: str, content: str, output_path: str) -> str:
        """Creates a simple formatted Word document."""
        from docx import Document
        doc = Document()
        doc.add_heading(title, level=1)
        doc.add_paragraph(content)
        os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)
        doc.save(output_path)
        return output_path

word_generator = WordGenerator()
